# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_window_add_pump.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class AddPumpDialog(object):
    def setupUi(self, Dialog, MainPumpsTable, HELPING):
        Dialog.setObjectName("Dialog")
        Dialog.resize(760, 929)
        Dialog.setMaximumSize(QtCore.QSize(760, 929))
        self.tableWidget_pump_enter = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_pump_enter.setGeometry(QtCore.QRect(40, 320, 695, 591))
        self.tableWidget_pump_enter.setObjectName("tableWidget_pump_enter")
        self.enter_data_from_db(MainPumpsTable, HELPING)
        self.label_pump_enter = QtWidgets.QLabel(Dialog)
        self.label_pump_enter.setGeometry(QtCore.QRect(270, 270, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_pump_enter.setFont(font)
        self.label_pump_enter.setObjectName("label_pump_enter")
        self.label_pump_enter_2 = QtWidgets.QLabel(Dialog)
        self.label_pump_enter_2.setGeometry(QtCore.QRect(250, 10, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_pump_enter_2.setFont(font)
        self.label_pump_enter_2.setObjectName("label_pump_enter_2")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(-50, 40, 821, 5))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(-20, 260, 821, 5))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(310, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.retry = QtWidgets.QPushButton(Dialog)
        self.retry.setGeometry(QtCore.QRect(530, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.retry.setFont(font)
        self.retry.setObjectName("retry")
        self.enter = QtWidgets.QPushButton(Dialog)
        self.enter.setGeometry(QtCore.QRect(630, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setGeometry(QtCore.QRect(420, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.tableWidget_pump_enter_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_pump_enter_2.setGeometry(QtCore.QRect(40, 60, 695, 161))
        self.tableWidget_pump_enter_2.setObjectName("tableWidget_pump_enter_2")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget_pump_enter_2.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem('Марка')
        item.setFont(font)
        self.tableWidget_pump_enter_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem('Ротор')
        item.setFont(font)
        self.tableWidget_pump_enter_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem('D, мм')
        item.setFont(font)
        self.tableWidget_pump_enter_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem('a')
        item.setFont(font)
        self.tableWidget_pump_enter_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem('b')
        item.setFont(font)
        self.tableWidget_pump_enter_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem('Qном')
        item.setFont(font)
        self.tableWidget_pump_enter_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem('k')
        item.setFont(font)
        self.tableWidget_pump_enter_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem('1')
        item.setFont(font)
        self.tableWidget_pump_enter_2.setRowCount(1)
        self.tableWidget_pump_enter_2.setVerticalHeaderItem(0, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def enter_data_from_db(self, MainPumpsTable, HELPING):
        self.tableWidget_pump_enter.setRowCount(0)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget_pump_enter.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem('Марка')
        item.setFont(font)
        self.tableWidget_pump_enter.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem('Ротор')
        item.setFont(font)
        self.tableWidget_pump_enter.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem('Диаметр рабочего колеса')
        item.setFont(font)
        self.tableWidget_pump_enter.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem('a')
        item.setFont(font)
        self.tableWidget_pump_enter.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem('b')
        item.setFont(font)
        self.tableWidget_pump_enter.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem('Qном')
        item.setFont(font)
        self.tableWidget_pump_enter.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem('k')
        item.setFont(font)
        self.tableWidget_pump_enter.setHorizontalHeaderItem(6, item)
        for index, pump in enumerate(MainPumpsTable.select()):
            self.tableWidget_pump_enter.setRowCount(index + 1)
            item = QtWidgets.QTableWidgetItem(f'{index + 1}')
            item.setFont(font)
            item.setToolTip(HELPING)
            self.tableWidget_pump_enter.setVerticalHeaderItem(index, item)
            brand = QtWidgets.QTableWidgetItem(str(pump.brand))
            brand.setFont(font)
            self.tableWidget_pump_enter.setItem(index, 0, brand)
            rotor = QtWidgets.QTableWidgetItem(str(pump.rotor))
            rotor.setFont(font)
            self.tableWidget_pump_enter.setItem(index, 1, rotor)
            impeller_diameter = QtWidgets.QTableWidgetItem(str(pump.impeller_diameter))
            impeller_diameter.setFont(font)
            self.tableWidget_pump_enter.setItem(index, 2, impeller_diameter)
            a = QtWidgets.QTableWidgetItem(str(pump.a))
            a.setFont(font)
            self.tableWidget_pump_enter.setItem(index, 3, a)
            b = QtWidgets.QTableWidgetItem(str(pump.b))
            b.setFont(font)
            self.tableWidget_pump_enter.setItem(index, 4, b)
            Qnom = QtWidgets.QTableWidgetItem(str(pump.Q_nom))
            Qnom.setFont(font)
            self.tableWidget_pump_enter.setItem(index, 5, Qnom)
            k = QtWidgets.QTableWidgetItem(str(pump.kaf))
            k.setFont(font)
            self.tableWidget_pump_enter.setItem(index, 6, k)
        self.tableWidget_pump_enter.resizeColumnsToContents()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление магистральных насосов"))
        self.label_pump_enter.setText(_translate("Dialog", "Список магистральных насосов"))
        self.label_pump_enter_2.setText(_translate("Dialog", "Добавление магистральных насосов"))
        self.cancel.setText(_translate("Dialog", "Отмена"))
        self.retry.setText(_translate("Dialog", "Сбросить"))
        self.enter.setText(_translate("Dialog", "Ввод"))
        self.add.setText(_translate("Dialog", "Добавить"))
