# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_window_add_pipe.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class AddPipeDialog(object):
    def setupUi(self, Dialog, PipeTable):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 929)
        Dialog.setMaximumSize(QtCore.QSize(519, 929))
        self.label_pump_enter_2 = QtWidgets.QLabel(Dialog)
        self.label_pump_enter_2.setGeometry(QtCore.QRect(160, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_pump_enter_2.setFont(font)
        self.label_pump_enter_2.setObjectName("label_pump_enter_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(-10, 50, 551, 5))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tableWidget_pipe_enter_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_pipe_enter_2.setGeometry(QtCore.QRect(10, 60, 501, 121))
        self.tableWidget_pipe_enter_2.setObjectName("tableWidget_pipe_enter_2")
        self.tableWidget_pipe_enter_2.setRowCount(1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget_pipe_enter_2.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem('Марка')
        item.setFont(font)
        self.tableWidget_pipe_enter_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem('Dн, мм')
        item.setFont(font)
        self.tableWidget_pipe_enter_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem('R1н, МПа')
        item.setFont(font)
        self.tableWidget_pipe_enter_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem('k1')
        item.setFont(font)
        self.tableWidget_pipe_enter_2.setHorizontalHeaderItem(3, item)
        self.cancel_2 = QtWidgets.QPushButton(Dialog)
        self.cancel_2.setGeometry(QtCore.QRect(220, 190, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cancel_2.setFont(font)
        self.cancel_2.setObjectName("cancel_2")
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setGeometry(QtCore.QRect(320, 190, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.retry = QtWidgets.QPushButton(Dialog)
        self.retry.setGeometry(QtCore.QRect(120, 190, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.retry.setFont(font)
        self.retry.setObjectName("retry")
        self.enter = QtWidgets.QPushButton(Dialog)
        self.enter.setGeometry(QtCore.QRect(420, 190, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(-10, 220, 531, 5))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_pump_enter = QtWidgets.QLabel(Dialog)
        self.label_pump_enter.setGeometry(QtCore.QRect(150, 230, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_pump_enter.setFont(font)
        self.label_pump_enter.setObjectName("label_pump_enter")
        self.tableWidget_pipe = QtWidgets.QTableWidget(Dialog)
        self.enter_data_table(PipeTable)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def enter_data_table(self, PipeTable):
        self.tableWidget_pipe.setGeometry(QtCore.QRect(10, 270, 501, 641))
        self.tableWidget_pipe.setObjectName("tableWidget_pipe")
        self.tableWidget_pipe.setRowCount(0)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget_pipe.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem('Марка трубы')
        item.setFont(font)
        self.tableWidget_pipe.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem('Dн, мм')
        item.setFont(font)
        self.tableWidget_pipe.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem('R1н, МПа')
        item.setFont(font)
        self.tableWidget_pipe.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem('k1')
        item.setFont(font)
        self.tableWidget_pipe.setHorizontalHeaderItem(3, item)
        for index, pipe in enumerate(PipeTable.select()):
            self.tableWidget_pipe.setRowCount(index + 1)
            item = QtWidgets.QTableWidgetItem(f'{index + 1}')
            item.setFont(font)
            self.tableWidget_pipe.setVerticalHeaderItem(index, item)
            brand = QtWidgets.QTableWidgetItem(str(pipe.brand))
            brand.setFont(font)
            self.tableWidget_pipe.setItem(index, 0, brand)
            diameter = QtWidgets.QTableWidgetItem(str(pipe.diameter))
            diameter.setFont(font)
            self.tableWidget_pipe.setItem(index, 1, diameter)
            R1n = QtWidgets.QTableWidgetItem(str(pipe.R1n))
            R1n.setFont(font)
            self.tableWidget_pipe.setItem(index, 2, R1n)
            k1 = QtWidgets.QTableWidgetItem(str(pipe.k1))
            k1.setFont(font)
            self.tableWidget_pipe.setItem(index, 3, k1)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_pump_enter_2.setText(_translate("Dialog", "Добавление марки трубы"))
        self.cancel_2.setText(_translate("Dialog", "Отмена"))
        self.add.setText(_translate("Dialog", "Добавить"))
        self.retry.setText(_translate("Dialog", "Сбросить"))
        self.enter.setText(_translate("Dialog", "Ввод"))
        self.label_pump_enter.setText(_translate("Dialog", "Список используемых труб"))
