# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_enter_pipe.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from settings import get_source_dict


class DnDialog(object):
    def setupUi(self, Dialog, var):
        Dialog.setObjectName("Dialog")
        Dialog.resize(499, 306)
        Dialog.setMaximumSize(QtCore.QSize(499, 306))
        dict_value = get_source_dict(var)
        Dn = int(dict_value['Dn'])
        self.R1n = QtWidgets.QLabel(Dialog)
        self.R1n.setGeometry(QtCore.QRect(10, 50, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.R1n.setFont(font)
        self.R1n.setObjectName("R1n")
        self.k1 = QtWidgets.QLabel(Dialog)
        self.k1.setGeometry(QtCore.QRect(10, 80, 311, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.k1.setFont(font)
        self.k1.setObjectName("k1")
        self.np = QtWidgets.QLabel(Dialog)
        self.np.setGeometry(QtCore.QRect(10, 110, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.np.setFont(font)
        self.np.setObjectName("np")
        self.kn = QtWidgets.QLabel(Dialog)
        self.kn.setGeometry(QtCore.QRect(10, 140, 331, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.kn.setFont(font)
        self.kn.setObjectName("kn")
        self.k_a = QtWidgets.QLabel(Dialog)
        self.k_a.setGeometry(QtCore.QRect(10, 170, 331, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.k_a.setFont(font)
        self.k_a.setObjectName("k_a")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(370, 50, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 80, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 110, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 140, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(370, 170, 113, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.enter = QtWidgets.QPushButton(Dialog)
        self.enter.setGeometry(QtCore.QRect(370, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        self.retry = QtWidgets.QPushButton(Dialog)
        self.retry.setGeometry(QtCore.QRect(260, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.retry.setFont(font)
        self.retry.setObjectName("retry")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(150, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(370, 200, 113, 22))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.k_a_2 = QtWidgets.QLabel(Dialog)
        self.k_a_2.setGeometry(QtCore.QRect(10, 200, 331, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.k_a_2.setFont(font)
        self.k_a_2.setObjectName("k_a_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setText(f'Наружный диаметр трубы составляет: {Dn} мм')
        self.choose = QtWidgets.QPushButton(Dialog)
        self.choose.setGeometry(QtCore.QRect(12, 230, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.choose.setFont(font)
        self.choose.setObjectName("choose")
        self.choose_k = QtWidgets.QPushButton(Dialog)
        self.choose_k.setGeometry(QtCore.QRect(10, 270, 181, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.choose_k.setFont(font)
        self.choose_k.setObjectName("choose_k")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Окно ввода характеристик трубы"))
        self.R1n.setText(_translate("Dialog", "Временное сопротивление стали, R1н"))
        self.k1.setText(_translate("Dialog", "Коэффициент надёжности по материалу, k1"))
        self.np.setText(_translate("Dialog", "Коэффициент надёжности по нагрузке, np"))
        self.kn.setText(_translate("Dialog", "Коэффициент надёжности по назначению, kн"))
        self.k_a.setText(_translate("Dialog", "Эквивалентная шероховатость трубы, kэ"))
        self.enter.setText(_translate("Dialog", "Ввод"))
        self.retry.setText(_translate("Dialog", "Сбросить"))
        self.cancel.setText(_translate("Dialog", "Отмена"))
        self.k_a_2.setText(_translate("Dialog", "Коэффициент условия работы, m"))
        self.label.setText(_translate("Dialog", "Наружный диаметр трубы составил:"))
        self.choose.setText(_translate("Dialog", "Выбрать трубу "))
        self.choose_k.setText(_translate("Dialog", "Выбрать коэффициенты"))
