# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_window_choose_pipe.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

HELPING = 'Кликните правой кнопкой кнопкой мыши по строчке коэффициента, который хотите выбрать. '


class ChoosePipeDialog(object):
    def setupUi(self, Dialog, PipeTable):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 720)
        Dialog.setMaximumSize(QtCore.QSize(519, 720))
        self.label_pump_enter = QtWidgets.QLabel(Dialog)
        self.label_pump_enter.setGeometry(QtCore.QRect(140, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_pump_enter.setFont(font)
        self.label_pump_enter.setObjectName("label_pump_enter")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(-10, 50, 531, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tableWidget_pipe = QtWidgets.QTableWidget(Dialog)
        self.label_pump_enter_2 = QtWidgets.QLabel(Dialog)
        self.label_pump_enter_2.setGeometry(QtCore.QRect(10, 610, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_pump_enter_2.setFont(font)
        self.label_pump_enter_2.setObjectName("label_pump_enter_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(320, 620, 41, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_pump_enter_3 = QtWidgets.QLabel(Dialog)
        self.label_pump_enter_3.setGeometry(QtCore.QRect(10, 640, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_pump_enter_3.setFont(font)
        self.label_pump_enter_3.setObjectName("label_pump_enter_3")
        self.label_pump_enter_4 = QtWidgets.QLabel(Dialog)
        self.label_pump_enter_4.setGeometry(QtCore.QRect(10, 670, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_pump_enter_4.setFont(font)
        self.label_pump_enter_4.setObjectName("label_pump_enter_4")
        self.enter_data_table(PipeTable)
        self.enter = QtWidgets.QPushButton(Dialog)
        self.enter.setGeometry(QtCore.QRect(380, 620, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        self.retry = QtWidgets.QPushButton(Dialog)
        self.retry.setGeometry(QtCore.QRect(320, 680, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.retry.setFont(font)
        self.retry.setObjectName("retry")
        self.cancel_2 = QtWidgets.QPushButton(Dialog)
        self.cancel_2.setGeometry(QtCore.QRect(420, 680, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cancel_2.setFont(font)
        self.cancel_2.setObjectName("cancel_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def enter_data_table(self, PipeTable):
        self.tableWidget_pipe.setGeometry(QtCore.QRect(10, 70, 501, 541))
        self.tableWidget_pipe.setObjectName("tableWidget_pipe")
        self.tableWidget_pipe.setRowCount(0)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget_pipe.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem('Марка стали')
        item.setFont(font)
        self.tableWidget_pipe.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem('Dн, мм')
        item.setFont(font)
        self.tableWidget_pipe.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem('R1н, МПа')
        item.setFont(font)
        self.tableWidget_pipe.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem('k1')
        item.setFont(font)
        self.tableWidget_pipe.setHorizontalHeaderItem(3, item)
        for index, pipe in enumerate(PipeTable.select()):
            self.tableWidget_pipe.setRowCount(index + 1)
            item = QtWidgets.QTableWidgetItem(f'{index + 1}')
            item.setFont(font)
            item.setToolTip(HELPING)
            self.tableWidget_pipe.setVerticalHeaderItem(index, item)
            brand = QtWidgets.QTableWidgetItem(str(pipe.brand))
            brand.setFont(font)
            self.tableWidget_pipe.setItem(index, 0, brand)
            diameter = QtWidgets.QTableWidgetItem(str(pipe.diameter))
            diameter.setFont(font)
            self.tableWidget_pipe.setItem(index, 1, diameter)
            R1n = QtWidgets.QTableWidgetItem(str(pipe.R1n))
            R1n.setFont(font)
            self.tableWidget_pipe.setItem(index, 2, R1n)
            k1 = QtWidgets.QTableWidgetItem(str(pipe.k1))
            k1.setFont(font)
            self.tableWidget_pipe.setItem(index, 3, k1)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_pump_enter.setText(_translate("Dialog", "Список используемых труб"))
        self.label_pump_enter_2.setText(_translate("Dialog", "Введите номер трубы в поле ввода:"))
        self.label_pump_enter_3.setText(_translate("Dialog", "Характеристики выбранной трубы, будут вставлены в поля"))
        self.label_pump_enter_4.setText(_translate("Dialog", "ввода."))
        self.enter.setText(_translate("Dialog", "Ввести"))
        self.retry.setText(_translate("Dialog", "Сбросить"))
        self.cancel_2.setText(_translate("Dialog", "Отмена"))
