# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
import json

from PyQt5 import QtCore, QtGui, QtWidgets
from models import ActionVarTable
from settings import SUP, SUP_2, SUP_3
from json import loads

TABLE_CHARACTIRISTICS_NAMES = ['Длина трассы, км', 'Длина участка, км', 'Рабочее давление, МПа',
                               'G, м\u00B3', 'kнп', 'Температура перекачки, К', 'Остаточный напор, м',
                               'Количество насосов на станции',
                               'Число рабочих дней']
LIST_TIPS_TABLE_CHARACTIRISTICS = ['Годовая производительность',
                                   '1,05 - трубопроводов, идущих параллельно с другими нефтепроводами и образующими систему\n'
                                   '1,1 - однониточных нефтепроводов, подающих нефть от пунктов добычи к системе трубопроводов\n'
                                   '1,07 - однониточных нефтепроводов, по которым нефть от системы нефтепроводов подается к нефтеперерабатывающему заводу,\n'
                                   'а также однониточных нефтепроводов, соединяющих систему']
TABLE_OIL_PROPERTIES_NAMES = ['Плотность, км/м\u00B3', 'Вязкость при t\u2081, мм\u00B2/c',
                              'Вязкость при t\u2082, мм\u00B2/c',
                              'T\u2081, K', 'T\u2082, K']
NUMBER_WORKING_DAYS = '350'


class MyWindow(object):
    def setupUi(self, MainWindow, MainPumpsTable):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_arrangement = QtWidgets.QFrame(self.tab)
        self.frame_arrangement.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_arrangement.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_arrangement.setObjectName("frame_arrangement")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_arrangement)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_arrangement)
        self.frame_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_2_5 = QtWidgets.QFrame(self.frame_arrangement)
        self.frame_2_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_5.setObjectName("frame_2_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5_5 = QtWidgets.QFrame(self.frame_2_5)
        self.frame_5_5.setMaximumSize(QtCore.QSize(282, 16777215))
        self.frame_5_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5_5.setObjectName("frame_5_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5_5)
        self.verticalLayout.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_5_5)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.tableWidget_charactiristics = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_charactiristics.setMaximumSize(QtCore.QSize(278, 16777215))
        self.tableWidget_charactiristics.setObjectName("tableWidget_charactiristics")
        self.tableWidget_charactiristics.setColumnCount(2)
        self.tableWidget_charactiristics.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_charactiristics.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_charactiristics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_charactiristics.setHorizontalHeaderItem(1, item)
        for index, name in enumerate(TABLE_CHARACTIRISTICS_NAMES):
            self.tableWidget_charactiristics.setRowCount(index + 1)
            item = QtWidgets.QTableWidgetItem(f'{index + 1}')
            item.setFont(font)
            self.tableWidget_charactiristics.setVerticalHeaderItem(index, item)
            name = QtWidgets.QTableWidgetItem(name)
            name.setFlags(QtCore.Qt.ItemIsEnabled)
            name.setFont(font)
            if index == 8:
                value = QtWidgets.QTableWidgetItem(NUMBER_WORKING_DAYS)
                self.tableWidget_charactiristics.setItem(index, 1, value)
            self.tableWidget_charactiristics.setItem(index, 0, name)
        self.tableWidget_charactiristics.verticalHeaderItem(3).setToolTip(LIST_TIPS_TABLE_CHARACTIRISTICS[0])
        self.tableWidget_charactiristics.verticalHeaderItem(4).setToolTip(LIST_TIPS_TABLE_CHARACTIRISTICS[1])
        self.tableWidget_charactiristics.resizeRowsToContents()
        self.verticalLayout_3.addWidget(self.tableWidget_charactiristics)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_9_5 = QtWidgets.QFrame(self.frame_5_5)
        self.frame_9_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9_5.setObjectName("frame_9_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9_5)
        self.verticalLayout_7.setContentsMargins(0, 12, 7, 54)
        self.verticalLayout_7.setSpacing(12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_9_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.tableWidget_oil_properties = QtWidgets.QTableWidget(self.frame_9_5)
        self.tableWidget_oil_properties.setMaximumSize(QtCore.QSize(278, 16777215))
        self.tableWidget_oil_properties.setObjectName("tableWidget_oil_properties")
        self.tableWidget_oil_properties.setColumnCount(2)
        self.tableWidget_oil_properties.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_oil_properties.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_oil_properties.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_oil_properties.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_oil_properties.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_oil_properties.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_oil_properties.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_oil_properties.setHorizontalHeaderItem(1, item)
        for index, name in enumerate(TABLE_OIL_PROPERTIES_NAMES):
            self.tableWidget_oil_properties.setRowCount(index + 1)
            item = QtWidgets.QTableWidgetItem(f'{index + 1}')
            item.setFont(font)
            self.tableWidget_oil_properties.setVerticalHeaderItem(index, item)
            name = QtWidgets.QTableWidgetItem(name)
            name.setFlags(QtCore.Qt.ItemIsEnabled)
            name.setFont(font)
            self.tableWidget_oil_properties.setItem(index, 0, name)
        self.tableWidget_oil_properties.resizeRowsToContents()
        self.verticalLayout_7.addWidget(self.tableWidget_oil_properties)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame_9_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.frame_5_5)
        self.frame_6_5 = QtWidgets.QFrame(self.frame_2_5)
        self.frame_6_5.setMaximumSize(QtCore.QSize(282, 16777215))
        self.frame_6_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6_5.setObjectName("frame_6_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6_5)
        self.verticalLayout_4.setContentsMargins(0, 12, 9, 0)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.frame_6_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.table = QtWidgets.QTableWidget(self.frame_6_5)
        self.table.setMaximumSize(QtCore.QSize(300, 16777215))
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item = QtWidgets.QTableWidgetItem()
        item.setFont(font)
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_4.addWidget(self.table)
        self.horizontalLayout.addWidget(self.frame_6_5)
        self.frame_7_5 = QtWidgets.QFrame(self.frame_2_5)
        self.frame_7_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7_5.setObjectName("frame_7_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7_5)
        self.verticalLayout_5.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_36 = QtWidgets.QLabel(self.frame_7_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_5.addWidget(self.label_36)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_7_5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem('Марка')
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem('Ротор')
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem('Диаметр рабочего колеса')
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem('a')
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem('b')
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        Q_nom = 'Qnom'.translate(SUP)
        item = QtWidgets.QTableWidgetItem(f'{Q_nom}' + f', м\N{SUPERSCRIPT THREE}')
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        for index, pump in enumerate(MainPumpsTable.select()):
            self.tableWidget.setRowCount(index + 1)
            item = QtWidgets.QTableWidgetItem(f'{index + 1}')
            item.setFont(font)
            self.tableWidget.setVerticalHeaderItem(index, item)
            brand = QtWidgets.QTableWidgetItem(str(pump.brand))
            brand.setFlags(QtCore.Qt.ItemIsEnabled)
            brand.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
            self.tableWidget.setItem(index, 0, brand)
            rotor = QtWidgets.QTableWidgetItem(str(pump.rotor))
            rotor.setFlags(QtCore.Qt.ItemIsEnabled)
            rotor.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
            self.tableWidget.setItem(index, 1, rotor)
            impeller_diameter = QtWidgets.QTableWidgetItem(str(pump.impeller_diameter))
            impeller_diameter.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
            impeller_diameter.setFlags(QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(index, 2, impeller_diameter)
            a = QtWidgets.QTableWidgetItem(str(pump.a))
            a.setFlags(QtCore.Qt.ItemIsEnabled)
            a.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
            self.tableWidget.setItem(index, 3, a)
            b = QtWidgets.QTableWidgetItem(str(pump.b))
            b.setFlags(QtCore.Qt.ItemIsEnabled)
            b.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
            self.tableWidget.setItem(index, 4, b)
            Qnom = QtWidgets.QTableWidgetItem(str(pump.Q_nom))
            Qnom.setFlags(QtCore.Qt.ItemIsEnabled)
            Qnom.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
            self.tableWidget.setItem(index, 5, Qnom)
        self.tableWidget.resizeColumnsToContents()
        self.tableWidget.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.horizontalLayout.addWidget(self.frame_7_5)
        self.frame_8 = QtWidgets.QFrame(self.frame_2_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_6.setSpacing(12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_31 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_8)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
        self.verticalLayout_6.addWidget(self.tableWidget_2)
        self.horizontalLayout.addWidget(self.frame_8)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 3)
        self.horizontalLayout.setStretch(3, 2)
        self.verticalLayout_2.addWidget(self.frame_2_5)
        self.frame_3 = QtWidgets.QFrame(self.frame_arrangement)
        self.frame_3.setMaximumSize(QtCore.QSize(1270, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_18 = QtWidgets.QFrame(self.frame_3)
        self.frame_18.setMaximumSize(QtCore.QSize(374, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_10.addWidget(self.pushButton_1, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_10.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_18)
        self.frame_21 = QtWidgets.QFrame(self.frame_3)
        self.frame_21.setMaximumSize(QtCore.QSize(592, 16777215))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_21)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.setVisible(False)
        self.gridLayout_7.addWidget(self.checkBox_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_21)
        self.frame_20 = QtWidgets.QFrame(self.frame_3)
        self.frame_20.setMaximumSize(QtCore.QSize(302, 16777215))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.checkBox = QtWidgets.QCheckBox(self.frame_20)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox.setVisible(False)
        self.gridLayout_9.addWidget(self.checkBox, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_20)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.frame_25 = QtWidgets.QFrame(self.frame_3)
        self.frame_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_4 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_4.setFont(font)
        font.setPointSize(12)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.progressBar = QtWidgets.QProgressBar(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_15.addWidget(self.progressBar)
        self.horizontalLayout_2.addWidget(self.frame_25)
        self.frame_25.close()
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 1)
        self.gridLayout_3.addWidget(self.frame_arrangement, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "Расстановка НПС")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_pipe = QtWidgets.QFrame(self.tab_2)
        self.frame_pipe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pipe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pipe.setObjectName("frame_pipe")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_pipe)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.frame_pipe)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 12, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_calc_var_7 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_calc_var_7.setFont(font)
        self.label_calc_var_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_calc_var_7.setObjectName("label_calc_var_7")
        self.horizontalLayout_3.addWidget(self.label_calc_var_7)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_pipe)
        self.frame_6.setEnabled(True)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(14)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_9.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_9.setSpacing(12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_calculated_data_7 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_calculated_data_7.setFont(font)
        self.label_calculated_data_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_calculated_data_7.setObjectName("label_calculated_data_7")
        self.verticalLayout_9.addWidget(self.label_calculated_data_7)
        self.table_date_7 = QtWidgets.QTableWidget(self.frame_7)
        self.table_date_7.setObjectName("table_date_7")
        self.table_date_7.setColumnCount(0)
        self.table_date_7.setRowCount(0)
        self.table_date_7.setMaximumSize(490, 16777215)
        self.verticalLayout_9.addWidget(self.table_date_7)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_category_7 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_category_7.setFont(font)
        self.label_category_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_category_7.setObjectName("label_category_7")
        self.verticalLayout_10.addWidget(self.label_category_7)
        self.label_category_8 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_category_8.setFont(font)
        self.label_category_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_category_8.setObjectName("label_category_8")
        self.verticalLayout_10.addWidget(self.label_category_8)
        self.table_category_7 = QtWidgets.QTableWidget(self.frame_9)
        self.table_category_7.setObjectName("table_category_7")
        self.table_category_7.setColumnCount(3)
        self.table_category_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_category_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_category_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_category_7.setHorizontalHeaderItem(2, item)
        self.table_category_7.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.table_category_7.horizontalHeaderItem(0).setToolTip("Категоря участка")
        self.table_category_7.horizontalHeaderItem(1).setToolTip("Длина участка")
        self.table_category_7.horizontalHeaderItem(2).setToolTip("Коэффициент условий работы трубопровода при расчете "
                                                                 "его на прочность, устойчивость и деформативность")
        self.verticalLayout_10.addWidget(self.table_category_7)
        self.frame_24 = QtWidgets.QFrame(self.frame_9)
        self.frame_24.setMaximumSize(QtCore.QSize(270, 16777215))
        self.frame_24.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(7)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.enter_categories_8 = QtWidgets.QPushButton(self.frame_24)
        self.enter_categories_8.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.enter_categories_8.setFont(font)
        self.enter_categories_8.setObjectName("enter_categories_8")
        self.horizontalLayout_15.addWidget(self.enter_categories_8)
        self.Add_2 = QtWidgets.QPushButton(self.frame_24)
        self.Add_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.Add_2.setFont(font)
        self.Add_2.setObjectName("Add_2")
        self.horizontalLayout_15.addWidget(self.Add_2)
        self.gridLayout_11.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_24)
        self.verticalLayout_10.setStretch(2, 11)
        self.verticalLayout_10.setStretch(3, 1)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_delta_7 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_delta_7.setFont(font)
        self.label_delta_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delta_7.setObjectName("label_delta_7")
        self.verticalLayout_11.addWidget(self.label_delta_7)
        self.label_delta_8 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_delta_8.setFont(font)
        self.label_delta_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delta_8.setObjectName("label_delta_8")
        self.verticalLayout_11.addWidget(self.label_delta_8)
        self.table_delta_7 = QtWidgets.QTableWidget(self.frame_10)
        self.table_delta_7.setObjectName("table_delta_7")
        self.table_delta_7.setColumnCount(2)
        self.table_delta_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        item.setFont(font)
        self.table_delta_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_delta_7.setHorizontalHeaderItem(1, item)
        self.table_delta_7.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.table_delta_7.horizontalHeaderItem(0).setToolTip("Категоря участка")
        self.table_delta_7.horizontalHeaderItem(1).setToolTip("Толщина стенки трубы на участке, мм")
        self.verticalLayout_11.addWidget(self.table_delta_7)
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_5.setStretch(2, 2)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_11 = QtWidgets.QFrame(self.frame_pipe)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_8.setSpacing(12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_calc_7 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_calc_7.setFont(font)
        self.label_calc_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_calc_7.setObjectName("label_calc_7")
        self.horizontalLayout_8.addWidget(self.label_calc_7)
        self.calculate_7 = QtWidgets.QPushButton(self.frame_12)
        self.calculate_7.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.calculate_7.setFont(font)
        self.calculate_7.setObjectName("calculate_7")
        self.horizontalLayout_8.addWidget(self.calculate_7)
        self.horizontalLayout_7.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_9.setContentsMargins(12, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_calc_delta_7 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_calc_delta_7.setFont(font)
        self.label_calc_delta_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_calc_delta_7.setObjectName("label_calc_delta_7")
        self.horizontalLayout_9.addWidget(self.label_calc_delta_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.calculate_with_delta = QtWidgets.QPushButton(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.calculate_with_delta.setFont(font)
        self.calculate_with_delta.setObjectName("calculate_with_delta")
        self.horizontalLayout_10.addWidget(self.calculate_with_delta)
        self.Add_delta = QtWidgets.QPushButton(self.frame_13)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.Add_delta.setFont(font)
        self.Add_delta.setObjectName("Add_delta")
        self.horizontalLayout_10.addWidget(self.Add_delta)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7.addWidget(self.frame_13)
        self.horizontalLayout_7.setStretch(0, 3)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.frame_14 = QtWidgets.QFrame(self.frame_pipe)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setContentsMargins(72, 12, 72, 0)
        self.verticalLayout_12.setSpacing(12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_recalc_data_7 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_recalc_data_7.setFont(font)
        self.label_recalc_data_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_recalc_data_7.setObjectName("label_recalc_data_7")
        self.verticalLayout_12.addWidget(self.label_recalc_data_7)
        self.table_finish_7 = QtWidgets.QTableWidget(self.frame_14)
        self.table_finish_7.setObjectName("table_finish_7")
        self.table_finish_7.setColumnCount(6)
        self.table_finish_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_finish_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_finish_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_finish_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_finish_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_finish_7.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        self.table_finish_7.setHorizontalHeaderItem(5, item)
        self.table_finish_7.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.table_finish_7.horizontalHeaderItem(2).setToolTip("Расчетное сопротивление металла трубы")
        self.table_finish_7.horizontalHeaderItem(3).setToolTip("Максимально допустимые напоры для участков")
        self.table_finish_7.horizontalHeaderItem(4).setToolTip("Напор создаваемый ПС")
        self.verticalLayout_12.addWidget(self.table_finish_7)
        self.verticalLayout_8.addWidget(self.frame_14)
        self.verticalLayout_8.setStretch(1, 8)
        self.verticalLayout_8.setStretch(2, 1)
        self.verticalLayout_8.setStretch(3, 8)
        self.gridLayout_4.addWidget(self.frame_pipe, 0, 0, 1, 1)
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_mode = QtWidgets.QFrame(self.tab_3)
        self.frame_mode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_mode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mode.setObjectName("frame_mode")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_mode)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_15 = QtWidgets.QFrame(self.frame_mode)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_var_8 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_var_8.setFont(font)
        self.label_var_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_var_8.setObjectName("label_var_8")
        self.gridLayout_5.addWidget(self.label_var_8, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_mode)
        self.frame_16.setMaximumSize(QtCore.QSize(1270, 16777215))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_16)
        self.frame.setMaximumSize(QtCore.QSize(373, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_22 = QtWidgets.QFrame(self.frame)
        self.frame_22.setMaximumSize(QtCore.QSize(391, 16777215))
        self.frame_22.setAutoFillBackground(False)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_hmin_8 = QtWidgets.QLabel(self.frame_22)
        self.label_hmin_8.setMaximumSize(QtCore.QSize(297, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_hmin_8.setFont(font)
        self.label_hmin_8.setAutoFillBackground(False)
        self.label_hmin_8.setObjectName("label_hmin_8")
        self.horizontalLayout_14.addWidget(self.label_hmin_8)
        self.lineEdit_hmin_8 = QtWidgets.QLineEdit(self.frame_22)
        self.lineEdit_hmin_8.setObjectName("lineEdit_hmin_8")
        self.horizontalLayout_14.addWidget(self.lineEdit_hmin_8)
        self.gridLayout_12.addWidget(self.frame_22, 0, 0, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_12)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setMaximumSize(QtCore.QSize(895, 16777215))
        self.frame_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_17.setAutoFillBackground(False)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_13.setContentsMargins(0, 0, 600, 0)
        self.horizontalLayout_13.setSpacing(12)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_23 = QtWidgets.QFrame(self.frame_17)
        self.frame_23.setMaximumSize(QtCore.QSize(295, 16777215))
        self.frame_23.setAutoFillBackground(False)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label__a_ = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label__a_.setFont(font)
        self.label__a_.setObjectName("label__a_")
        self.horizontalLayout_12.addWidget(self.label__a_)
        self.lineEdit_a_ = QtWidgets.QLineEdit(self.frame_23)
        self.lineEdit_a_.setObjectName("lineEdit_a_")
        self.horizontalLayout_12.addWidget(self.lineEdit_a_)
        self.calculate_8 = QtWidgets.QPushButton(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.calculate_8.setFont(font)
        self.calculate_8.setObjectName("calculate_8")
        self.horizontalLayout_12.addWidget(self.calculate_8)
        self.retry_8 = QtWidgets.QPushButton(self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.retry_8.setFont(font)
        self.retry_8.setObjectName("retry_8")
        self.horizontalLayout_12.addWidget(self.retry_8)
        self.horizontalLayout_13.addWidget(self.frame_23)
        self.horizontalLayout_4.addWidget(self.frame_17)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.verticalLayout_13.addWidget(self.frame_16)
        self.frame_19 = QtWidgets.QFrame(self.frame_mode)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_14.setContentsMargins(0, 12, 0, 0)
        self.verticalLayout_14.setSpacing(12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_title_table_8 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_title_table_8.setFont(font)
        self.label_title_table_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_table_8.setObjectName("label_title_table_8")
        self.verticalLayout_14.addWidget(self.label_title_table_8)
        self.tableWidget_8 = QtWidgets.QTableWidget(self.frame_19)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.verticalLayout_14.addWidget(self.tableWidget_8)
        self.verticalLayout_13.addWidget(self.frame_19)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_13.setStretch(1, 2)
        self.verticalLayout_13.setStretch(2, 19)
        self.gridLayout_6.addWidget(self.frame_mode, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setObjectName("menubar")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setFont(font)
        self.menu_5.setObjectName("menu_5")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu.setFont(font)
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setFont(font)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_kaf = QtWidgets.QAction(MainWindow)
        self.action_kaf.setObjectName("action_kaf")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_new_var = QtWidgets.QAction(MainWindow)
        self.action_new_var.setObjectName("action_new_var")
        self.action_delet = QtWidgets.QAction(MainWindow)
        self.action_delet.setObjectName("action_delet")
        self.action_xls = QtWidgets.QAction(MainWindow)
        self.action_xls.setObjectName("action_xls")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu_5.addAction(self.action_new_var)
        self.menu_5.addAction(self.action_save)
        self.menu_5.addAction(self.action_delet)
        self.menu_5.addAction(self.action_xls)
        self.menu_5.addAction(self.action_5)
        self.menu_3.addAction(self.action_2)
        self.menu_3.addAction(self.action_4)
        self.menu_3.addAction(self.action_7)
        self.menu_3.addAction(self.action_kaf)
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.dict_menu_var = {}
        open = 'Открыть'
        delete = 'Удалить'
        for var in ActionVarTable.select():
            self.dict_menu_var[var.var] = []
            self.dict_menu_var[var.var].append(QtWidgets.QMenu(parent=self.menu, title=var.var))
            list_action = [QtWidgets.QAction(parent=MainWindow, text=open), QtWidgets.QAction(parent=MainWindow, text=delete)]
            list_action[0].setFont(font)
            list_action[1].setFont(font)
            self.dict_menu_var[var.var].append(list_action)
            self.dict_menu_var[var.var][0].addAction(list_action[0])
            self.dict_menu_var[var.var][0].addAction(list_action[1])
            self.menu.addMenu(self.dict_menu_var[var.var][0])

        self.shower = QtWidgets.QPushButton(self.frame_arrangement)
        self.shower.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.shower.setFont(font)
        self.shower.setObjectName("shower")
        self.shower.setText("Показать графику")
        self.gridLayout_10.addWidget(self.shower, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6_5)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 21)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_24)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setMaximumSize(63, 22)
        self.gridLayout_11.addWidget(self.lineEdit_2, 0, 1, 1, 1)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное окно"))
        self.label.setText(_translate("MainWindow", "Название варианта: Новый"))
        self.label_2.setText(_translate("MainWindow", "Характеристика трассы"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_charactiristics.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_charactiristics.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя "))
        item = self.tableWidget_charactiristics.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        self.label_3.setText(_translate("MainWindow", "Свойства нефти"))
        item = self.tableWidget_oil_properties.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_oil_properties.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_oil_properties.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_oil_properties.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_oil_properties.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_oil_properties.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя "))
        item = self.tableWidget_oil_properties.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        self.label_28.setText(_translate("MainWindow", "Координаты трассы"))
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "x"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "z"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить"))
        self.label_36.setText(_translate("MainWindow", "Список насосов"))
        self.label_31.setText(_translate("MainWindow", "Итоговые результаты"))
        self.label_4.setText(_translate("MainWindow", "Прогресс расчета"))
        self.pushButton_1.setText(_translate("MainWindow", "Рассчитать"))
        self.pushButton_2.setText(_translate("MainWindow", "Сбросить"))
        self.checkBox_2.setText(_translate("MainWindow", "Показать эпюру в отдельном окне приложеня"))
        self.checkBox.setText(_translate("MainWindow", "Произвести построение в AutoCAD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Расстановка НПС"))
        self.label_calc_var_7.setText(_translate("MainWindow", "Название варианта: Новый"))
        self.label_calculated_data_7.setText(_translate("MainWindow", "Расчётные данные"))
        self.label_category_7.setText(_translate("MainWindow", " Уточненные категории участков и коэффициенты "))
        self.label_category_8.setText(_translate("MainWindow", "условий работы"))
        item = self.table_category_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Категория участка"))
        item = self.table_category_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "L, км"))
        item = self.table_category_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "m"))
        self.enter_categories_8.setText(_translate("MainWindow", "Ввод"))
        self.Add_2.setText(_translate("MainWindow", "Добавить"))
        self.label_delta_7.setText(_translate("MainWindow", "Изменённые толщины стенок "))
        self.label_delta_8.setText(_translate("MainWindow", "трубопровода на участках"))
        item = self.table_delta_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Кат. участка"))
        item = self.table_delta_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "δ, мм"))
        self.label_calc_7.setText(_translate("MainWindow", "Рассчитать без изменений толщин стенок трубопровода:"))
        self.calculate_7.setText(_translate("MainWindow", "Рассчитать"))
        self.label_calc_delta_7.setText(_translate("MainWindow", "Рассчитать с изменёнными толщинами:"))
        self.calculate_with_delta.setText(_translate("MainWindow", "Рассчитать"))
        self.Add_delta.setText(_translate("MainWindow", "Добавить"))
        self.label_recalc_data_7.setText(
            _translate("MainWindow", "Перерасчёт максимально допустимыйх напоров на участках трубопровода"))
        item = self.table_finish_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Категория участка"))
        item = self.table_finish_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Толщина стенки, мм"))
        item = self.table_finish_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "R\u2081, МПа"))
        item = self.table_finish_7.horizontalHeaderItem(3)
        Hmax = "Hmax, м".translate(SUP_2)
        item.setText(_translate("MainWindow", Hmax))
        item = self.table_finish_7.horizontalHeaderItem(4)
        Hps = "Hps,м".translate(SUP_3)
        item.setText(_translate("MainWindow", Hps))
        item = self.table_finish_7.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Соответствие"))
        self.label_var_8.setText(_translate("MainWindow", "Название варианта: Новый"))
        self.label_hmin_8.setText(_translate("MainWindow", "Разрешённое значение подпора, м:"))
        self.label__a_.setText(_translate("MainWindow", "a\':"))
        self.calculate_8.setText(_translate("MainWindow", "Рассчитать"))
        self.retry_8.setText(_translate("MainWindow", "Сбросить"))
        self.label_title_table_8.setText(
            _translate("MainWindow", "Режимы эксплуатации трубопровода для первого эксплуатационного участка"))
        self.menu_5.setTitle(_translate("MainWindow", "Меню"))
        self.menu.setTitle(_translate("MainWindow", "Вариант"))
        self.menu_3.setTitle(_translate("MainWindow", "Внести в базу оборудование, коэффициент"))
        self.action_2.setText(_translate("MainWindow", "Добавить магистральный насос"))
        self.action_kaf.setText(_translate("MainWindow", "Добавить коэффициент в базу"))
        self.action_4.setText(_translate("MainWindow", "Добавить подпорный насос"))
        self.action_7.setText(_translate("MainWindow", "Добавить трубу"))
        self.action_save.setText(_translate("MainWindow", "Сохранить вариант"))
        self.action_new_var.setText(_translate("MainWindow", "Новый вариант"))
        self.action_delet.setText(_translate("MainWindow", "Удалить все варианты"))
        self.action_xls.setText(_translate("MainWindow", "Экспорт в xls"))
        self.action_5.setText(_translate("MainWindow", "Справка"))
